CREATE TABLE `Untitled` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Key2`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `Untitled4` (
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `CopyOfUntitled3` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `CopyOfUntitled` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `CopyOfUntitled4` (
	`Key3`	VARCHAR(255)	NOT NULL,
	`Key`	VARCHAR(255)	NOT NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled2` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `CopyOfCopyOfUntitled` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled3` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled5` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `Untitled6` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL,
	`Field9`	VARCHAR(255)	NULL,
	`Field10`	VARCHAR(255)	NULL,
	`Field11`	VARCHAR(255)	NULL,
	`Field12`	VARCHAR(255)	NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `Untitled7` (
	`Key`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

ALTER TABLE `Untitled` ADD CONSTRAINT `PK_UNTITLED` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `PK_UNTITLED4` PRIMARY KEY (
	`Key3`
);

ALTER TABLE `CopyOfUntitled3` ADD CONSTRAINT `PK_COPYOFUNTITLED3` PRIMARY KEY (
	`Key`
);

ALTER TABLE `CopyOfUntitled` ADD CONSTRAINT `PK_COPYOFUNTITLED` PRIMARY KEY (
	`Key`
);

ALTER TABLE `CopyOfUntitled4` ADD CONSTRAINT `PK_COPYOFUNTITLED4` PRIMARY KEY (
	`Key3`,
	`Key`,
	`Key2`
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `PK_UNTITLED2` PRIMARY KEY (
	`Key`
);

ALTER TABLE `CopyOfCopyOfUntitled` ADD CONSTRAINT `PK_COPYOFCOPYOFUNTITLED` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled3` ADD CONSTRAINT `PK_UNTITLED3` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `PK_UNTITLED5` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled6` ADD CONSTRAINT `PK_UNTITLED6` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled7` ADD CONSTRAINT `PK_UNTITLED7` PRIMARY KEY (
	`Key`
);

ALTER TABLE `CopyOfUntitled4` ADD CONSTRAINT `FK_CopyOfCopyOfUntitled_TO_CopyOfUntitled4_1` FOREIGN KEY (
	`Key`
)
REFERENCES `CopyOfCopyOfUntitled` (
	`Key`
);

ALTER TABLE `CopyOfUntitled4` ADD CONSTRAINT `FK_CopyOfUntitled3_TO_CopyOfUntitled4_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `CopyOfUntitled3` (
	`Key`
);

